[project]
name = "filemason"
version = "0.1.0"
description = "a config-driven file organizing cli tool"
authors = [{name = "Karson Bryant"}]
readme = "README.md"
dependencies = []
requires-python = ">=3.12.4"

[project.scripts]
filemason = "filemason.cli:main"




